# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DocopsBeta < Formula
  desc "Typed project-state substrate for LLM-first software development (beta channel)"
  homepage "https://github.com/logicwind/DocOps"
  version "0.8.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/logicwind/DocOps/releases/download/v0.8.0-beta.1/docops_0.8.0-beta.1_darwin_x86_64.tar.gz"
      sha256 "3506578ede39157e439bb8d4ef2a073fd14f237b950d872352259f75788ed437"

      define_method(:install) do
        bin.install "docops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/logicwind/DocOps/releases/download/v0.8.0-beta.1/docops_0.8.0-beta.1_darwin_arm64.tar.gz"
      sha256 "b0722653a3cb551ac6f5fe05942af066982939f29fec38b68d2c08ea73a4d024"

      define_method(:install) do
        bin.install "docops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/logicwind/DocOps/releases/download/v0.8.0-beta.1/docops_0.8.0-beta.1_linux_x86_64.tar.gz"
      sha256 "cd3d3a040bdf8b7c885f59062abc2eb121262673f88b7c3c1c1ca2de45a7af8e"
      define_method(:install) do
        bin.install "docops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logicwind/DocOps/releases/download/v0.8.0-beta.1/docops_0.8.0-beta.1_linux_arm64.tar.gz"
      sha256 "726fe3363c962b133bb1ca3d429e1aa5a783451491f2fe4f9e4d0bf733da1612"
      define_method(:install) do
        bin.install "docops"
      end
    end
  end

  test do
    system "#{bin}/docops --version"
  end
end
