# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docops@beta < Formula
  desc "Typed project-state substrate for LLM-first software development (beta channel)"
  homepage "https://github.com/logicwind/DocOps"
  version "0.7.1-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/logicwind/DocOps/releases/download/v0.7.1-beta.1/docops_0.7.1-beta.1_darwin_x86_64.tar.gz"
      sha256 "6b41226e6e1b1355ebf1059a7b302fd8601083f17c9f9d49d17fd4ea69018941"

      define_method(:install) do
        bin.install "docops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/logicwind/DocOps/releases/download/v0.7.1-beta.1/docops_0.7.1-beta.1_darwin_arm64.tar.gz"
      sha256 "7820ce8182ff746bd2473559fdc2ad2397394fa0f2d89579d09a13a752cfd83d"

      define_method(:install) do
        bin.install "docops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/logicwind/DocOps/releases/download/v0.7.1-beta.1/docops_0.7.1-beta.1_linux_x86_64.tar.gz"
      sha256 "5f9cfc344a7cf54ba6a32c25003f1530a5437ec3ce80cb1d4815adb751a5abbe"
      define_method(:install) do
        bin.install "docops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logicwind/DocOps/releases/download/v0.7.1-beta.1/docops_0.7.1-beta.1_linux_arm64.tar.gz"
      sha256 "1901fb372914334de872f4ebf3be47470fc9b9baeb327a0d19dd6aadcc7eb535"
      define_method(:install) do
        bin.install "docops"
      end
    end
  end

  test do
    system "#{bin}/docops --version"
  end
end
