# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DocopsBeta < Formula
  desc "Typed project-state substrate for LLM-first software development (beta channel)"
  homepage "https://github.com/logicwind/DocOps"
  version "0.7.1-beta.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/logicwind/DocOps/releases/download/v0.7.1-beta.2/docops_0.7.1-beta.2_darwin_x86_64.tar.gz"
      sha256 "a18600b0b06cca8921dbc20bb08f8f9606109ad91be09464799556b0a91f1f23"

      define_method(:install) do
        bin.install "docops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/logicwind/DocOps/releases/download/v0.7.1-beta.2/docops_0.7.1-beta.2_darwin_arm64.tar.gz"
      sha256 "ad93a131098b4f48ff27369e225a21977fc7e267c67a6cc8813447eb1de0d6e9"

      define_method(:install) do
        bin.install "docops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/logicwind/DocOps/releases/download/v0.7.1-beta.2/docops_0.7.1-beta.2_linux_x86_64.tar.gz"
      sha256 "425ed5fdb5c8d82e461356a432a876ee564fee673f988a3a6146e5e208056d8e"
      define_method(:install) do
        bin.install "docops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logicwind/DocOps/releases/download/v0.7.1-beta.2/docops_0.7.1-beta.2_linux_arm64.tar.gz"
      sha256 "d39e45a3eb278645781b54d3bbaee85be343e90fa4f6f3c9f2995b1f4f9fcb48"
      define_method(:install) do
        bin.install "docops"
      end
    end
  end

  test do
    system "#{bin}/docops --version"
  end
end
