# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docops < Formula
  desc "Typed project-state substrate for LLM-first software development"
  homepage "https://github.com/logicwind/DocOps"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/logicwind/DocOps/releases/download/v0.6.0/docops_0.6.0_darwin_x86_64.tar.gz"
      sha256 "5b977b64680a693678db15db6adfc241c9d680f57b38abe4b73e485f13097bf0"

      define_method(:install) do
        bin.install "docops"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/logicwind/DocOps/releases/download/v0.6.0/docops_0.6.0_darwin_arm64.tar.gz"
      sha256 "e9e9dde1220384dd704d5d60367806b073351850189c50bae7911c45a7adaffd"

      define_method(:install) do
        bin.install "docops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/logicwind/DocOps/releases/download/v0.6.0/docops_0.6.0_linux_x86_64.tar.gz"
      sha256 "5ed376f5683ea4401d631a3772bc3f68a1268bc4007cc4bda434606db016e0e3"
      define_method(:install) do
        bin.install "docops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/logicwind/DocOps/releases/download/v0.6.0/docops_0.6.0_linux_arm64.tar.gz"
      sha256 "574cf55299eeedd5824c4f7b588f7f741c56854e21d73baa393d013afc7ed35c"
      define_method(:install) do
        bin.install "docops"
      end
    end
  end

  test do
    system "#{bin}/docops --version"
  end
end
